# Makefile for animation programs for Wowwee Chimp

all: animateA animateB

animateA: animateA.c
	gcc -g -Wall -o animateA animateA.c -lwiringPi

animeateB: animateB.c
	gcc -g -Wall -o animateB animateB.c -lwiringPi

clean:
	rm -f animateA animateB
